Repository Nexters/mozipmozip, pull requests merged in 2020-02, with the labels that each got.

#39 [프론트] Admin 헤더 정의(와이어 프레임 기준)
  mozip-client/package.json
  mozip-client/public/index.html
  mozip-client/src/App.tsx
  mozip-client/src/components/Admin/Announcement/Create/Intro/index.tsx
  mozip-client/src/components/Admin/Announcement/Create/index.scss
  mozip-client/src/components/Admin/Announcement/Create/index.tsx
  mozip-client/src/components/Admin/Main/index.tsx
  mozip-client/src/components/Admin/Main/styled.ts
  mozip-client/src/components/common/Admin/Header/index.scss
  mozip-client/src/components/common/Admin/Header/index.tsx
  mozip-client/src/components/common/Admin/Header/style.ts
  mozip-client/src/components/common/Admin/HeaderCategory/index.scss
  mozip-client/src/components/common/Admin/HeaderCategory/index.tsx
  mozip-client/src/components/common/Admin/HeaderCategory/style.ts
  mozip-client/src/components/common/Admin/Layout.tsx
  mozip-client/src/components/common/Admin/ProgressBar/index.scss
  mozip-client/src/components/common/Admin/ProgressBar/index.tsx
  mozip-client/src/components/common/Admin/index.tsx
  mozip-client/src/components/common/Common.tsx
  mozip-client/src/index.css
  mozip-client/src/index.tsx
  mozip-client/src/modules/employees/sagas.ts
  mozip-client/src/pages/AdminPage.tsx
  mozip-client/src/pages/MainPage.tsx
  mozip-client/src/pages/index.ts
Labels: FE

#47 [#44] Add api doc - swagger api
  mozip-client/yarn.lock
  mozip-server/mozip-api/build.gradle
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/config/SwaggerConfig.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/config/WebMvcConfigForReact.java
Labels: BE, documentation

#32 [ Feature / issue 25 ] Add Resume Domain
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/controller/ResumeController.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeAnswerItemCreateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeAnswerItemUpdateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeCreateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeUpdateDto.java
  mozip-server/mozip-api/src/test/java/org/nexters/mozipmozip/resume/ResumeControllerTest.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/application/ResumeService.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/Resume.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/ResumeAnswerItem.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/ResumeOccupation.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/ResumeRepository.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/ResumeState.java
  mozip-server/mozip-domain/src/test/java/org/nexters/mozipmozip/resume/application/ResumeServiceTest.java
Labels: BE, feature

#56 [#51] Add github workflow for ecs deploy
  .github/workflows/build.yml
  .github/workflows/deploy-ecs.yml
  mozip-client/src/pages/MainPage.tsx
  task-definition.json
Labels: BE, feature

#35 [#26] 로그인/회원가입
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/member/controller/UserController.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/user/controller/UserController.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/user/dto/UserCreateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/user/dto/UserGetDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/user/dto/UserLoginDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/user/dto/UserUpdateDto.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/member/application/UserService.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/Resume.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/user/application/UserService.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/user/domain/User.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/user/domain/UserRepositoy.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/user/exception/UserDefineException.java
  mozip-server/mozip-domain/src/test/java/org/nexters/mozipmozip/member/application/UserServiceTest.java
  mozip-server/mozip-domain/src/test/java/org/nexters/mozipmozip/user/application/UserServiceTest.java
Labels: BE, feature

#66 공통적인 스타일 수정
  mozip-client/src/components/common/Header/index.scss
  mozip-client/src/components/common/Header/index.tsx
  mozip-client/src/index.css
Labels: FE

#69 회원가입 페이지 UI 구현
  mozip-client/src/App.tsx
  mozip-client/src/components/common/InputForm/index.tsx
  mozip-client/src/components/common/InputForm/style.ts
  mozip-client/src/containers/SignUp/Applicant/index.tsx
  mozip-client/src/containers/SignUp/Manager/index.tsx
  mozip-client/src/containers/SignUp/SignUpContainer/index.tsx
  mozip-client/src/containers/SignUp/SignUpContainer/style.ts
  mozip-client/src/pages/SignUpPage.tsx
  mozip-client/src/pages/index.ts
Labels: FE

#68 Feature/issue 40 [모집공고 제작]
  mozip-client/package.json
  mozip-client/src/App.tsx
  mozip-client/src/components/Admin/Announcement/Create/CommonQuestion/index.tsx
  mozip-client/src/components/Admin/Announcement/Create/Intro/index.tsx
  mozip-client/src/components/Admin/Announcement/Create/Intro/styled.ts
  mozip-client/src/components/Admin/Announcement/Create/Question/index.tsx
  mozip-client/src/components/Admin/Announcement/Create/Question/styled.ts
  mozip-client/src/components/Admin/Announcement/Create/index.scss
  mozip-client/src/components/Admin/Announcement/Create/index.tsx
  mozip-client/src/components/Admin/Announcement/Create/styled.ts
  mozip-client/src/components/common/Admin/Calendar/Calendar.tsx
  mozip-client/src/components/common/Admin/ProgressBar/index.scss
  mozip-client/src/components/common/Admin/ProgressBar/index.tsx
  mozip-client/src/hooks/index.ts
  mozip-client/src/hooks/useAdmin.tsx
  mozip-client/src/index.css
  mozip-client/src/lib/jimp.ts
  mozip-client/src/modules/admin/actions.ts
  mozip-client/src/modules/admin/index.ts
  mozip-client/src/modules/admin/reducer.ts
  mozip-client/src/modules/admin/types.ts
  mozip-client/src/modules/default.ts
  mozip-client/src/modules/index.ts
  mozip-client/src/pages/AdminPage.tsx
  mozip-client/src/pages/MainPage.tsx
  mozip-client/yarn.lock
Labels: FE, feature

#76 [#00] feat - add current user api
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/user/controller/UserController.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/user/dto/UserGetDto.java
  mozip-server/mozip-api/src/test/java/org/nexters/mozipmozip/member/controller/UserControllerTest.java
  mozip-server/mozip-api/src/test/java/org/nexters/mozipmozip/notice/NoticeControllerTest.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/user/domain/User.java
Labels: BE, feature

#75 Resume API 수정
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/controller/ResumeController.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeAnswerItemCreateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeCreateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeStateUpdateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeUpdateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeViewDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeViewDtoByNoticeId.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeViewDtoByUserId.java
  mozip-server/mozip-api/src/test/java/org/nexters/mozipmozip/resume/ResumeControllerTest.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/application/ResumeService.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/Resume.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/ResumeAnswerItem.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/ResumeJobType.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/ResumeRepository.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/ResumeState.java
  mozip-server/mozip-domain/src/test/java/org/nexters/mozipmozip/resume/application/ResumeServiceTest.java
Labels: BE, bug

#85 [ Develop to Master ] 지원서 테스트 수정
  mozip-server/mozip-domain/src/test/java/org/nexters/mozipmozip/resume/application/ResumeServiceTest.java
Labels: BE

#88 지원자 서류작성 상태 관리 기능
  mozip-client/src/App.tsx
  mozip-client/src/components/Admin/Announcement/Create/CommonQuestion/index.tsx
  mozip-client/src/components/Admin/Announcement/Create/index.tsx
  mozip-client/src/components/common/inputBox/index.tsx
  mozip-client/src/components/common/inputBox/styled.ts
  mozip-client/src/components/user/banner/index.tsx
  mozip-client/src/components/users/banner/index.tsx
  mozip-client/src/components/users/banner/styled.ts
  mozip-client/src/components/users/resumes/create/index.tsx
  mozip-client/src/components/users/resumes/create/userInfo/index.tsx
  mozip-client/src/components/users/resumes/create/userInfo/styled.ts
  mozip-client/src/components/users/resumes/main/index.tsx
  mozip-client/src/containers/SignUp/SignUpContainer/style.ts
  mozip-client/src/hooks/index.ts
  mozip-client/src/hooks/useResumes.tsx
  mozip-client/src/modules/admin/actions.ts
  mozip-client/src/modules/admin/reducer.ts
  mozip-client/src/modules/index.ts
  mozip-client/src/modules/resumes/actions.ts
  mozip-client/src/modules/resumes/index.ts
  mozip-client/src/modules/resumes/reducer.ts
  mozip-client/src/pages/MainPage.tsx
  mozip-client/src/pages/resumes.tsx
  mozip-client/src/pages/user/infoform/index.tsx
  mozip-client/tsconfig.json
Labels: FE, feature

#79 회원가입 페이지
  mozip-client/src/components/common/InputForm/index.tsx
  mozip-client/src/containers/SignUp/Applicant/index.tsx
  mozip-client/src/containers/SignUp/Manager/index.tsx
  mozip-client/src/containers/SignUp/SignUpContainer/index.tsx
  mozip-client/src/containers/SignUp/SignUpContainer/style.ts
Labels: FE

#81 로그인 페이지 UI
  mozip-client/src/App.tsx
  mozip-client/src/containers/SignIn/SignInContainer/index.tsx
  mozip-client/src/containers/SignIn/SignInContainer/style.ts
  mozip-client/src/pages/SignInPage.tsx
  mozip-client/src/pages/index.ts
  mozip-client/src/static/images/logo-title.png
  mozip-client/src/static/images/logo.png
Labels: FE

#83 헤더 로고 추가
  mozip-client/src/components/common/Header/index.scss
  mozip-client/src/components/common/Header/index.tsx
  mozip-client/src/index.css
Labels: FE

#87 메인 페이지 UI
  mozip-client/src/containers/Main/MainContainer/index.tsx
  mozip-client/src/containers/Main/MainContainer/style.ts
  mozip-client/src/index.css
  mozip-client/src/pages/MainPage.tsx
  mozip-client/src/static/images/main-image.png
Labels: FE

#64 InterviewTeam 정의
  mozip-client/src/index.tsx
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/interviewTeam/controller/InterviewTeamController.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/interviewTeam/dto/CreateInterviewTeamDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/interviewTeam/dto/GetInterviewTeamDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/user/controller/UserController.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/user/dto/UserLoginDto.java
  mozip-server/mozip-api/src/test/java/org/nexters/mozipmozip/interviewTeam/InterviewTeamControllerTest.java
  mozip-server/mozip-api/src/test/java/org/nexters/mozipmozip/member/controller/UserControllerTest.java
  mozip-server/mozip-api/src/test/java/org/nexters/mozipmozip/user/UserControllerTest.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/interviewTeam/application/InterviewTeamService.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/interviewTeam/domian/InterviewTeam.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/interviewTeam/domian/InterviewTeamRepository.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/user/domain/User.java
  mozip-server/mozip-domain/src/test/java/org/nexters/mozipmozip/interviewTeam/application/InterviewTeamServiceTest.java
  mozip-server/mozip-domain/src/test/java/org/nexters/mozipmozip/user/application/UserServiceTest.java
Labels: BE

#95 헤더 디자인 수정
  mozip-client/src/components/common/Admin/index.tsx
  mozip-client/src/components/common/Header/index.scss
  mozip-client/src/components/common/Header/index.tsx
  mozip-client/src/components/common/HeaderCategory/index.scss
  mozip-client/src/components/common/HeaderCategory/index.tsx
  mozip-client/src/components/common/HeaderCategory/style.ts
  mozip-client/src/components/common/Layout.tsx
  mozip-client/src/components/common/Navigation/index.tsx
  mozip-client/src/components/common/Navigation/style.ts
  mozip-client/src/containers/Main/MainContainer/index.tsx
  mozip-client/src/pages/AdminPage.tsx
  mozip-client/src/pages/MainPage.tsx
  mozip-client/src/pages/Resumes.tsx
  mozip-client/src/pages/SignInPage.tsx
  mozip-client/src/pages/SignUpPage.tsx
  mozip-client/src/static/images/banner.png
Labels: FE

#97 지원-서류작성 페이지 UI
  mozip-client/src/components/common/InputForm/style.ts
  mozip-client/src/components/common/inputBox/index.tsx
  mozip-client/src/components/common/inputBox/styled.ts
  mozip-client/src/components/users/answerBox/index.tsx
  mozip-client/src/components/users/answerBox/styled.ts
  mozip-client/src/components/users/banner/index.tsx
  mozip-client/src/components/users/banner/styled.ts
  mozip-client/src/components/users/question/index.tsx
  mozip-client/src/components/users/resumes/create/answers/index.tsx
  mozip-client/src/components/users/resumes/create/answers/styled.ts
  mozip-client/src/components/users/resumes/create/index.tsx
  mozip-client/src/components/users/resumes/create/userInfo/index.tsx
  mozip-client/src/components/users/resumes/create/userInfo/styled.ts
  mozip-client/src/containers/Main/MainContainer/index.tsx
  mozip-client/src/containers/Main/MainContainer/style.ts
  mozip-client/src/index.css
  mozip-client/src/modules/resumes/reducer.ts
  mozip-client/src/pages/resumes.tsx
  mozip-client/src/static/images/uploadImg.png
Labels: FE, feature

#100 어드민 페이지 디자인
  mozip-client/src/components/Admin/Main/index.tsx
  mozip-client/src/components/Admin/Main/styled.ts
  mozip-client/src/components/common/Button/index.tsx
  mozip-client/src/components/common/Button/style.ts
  mozip-client/src/containers/Admin/MainContainer/index.tsx
  mozip-client/src/containers/Admin/MainContainer/styled.ts
  mozip-client/src/pages/AdminPage.tsx
Labels: FE

#113 지원자 서류작성 리덕스 상태 관리 기능 추가
  mozip-client/src/components/users/answerBox/index.tsx
  mozip-client/src/components/users/resumes/create/answers/index.tsx
  mozip-client/src/components/users/resumes/create/answers/styled.ts
  mozip-client/src/components/users/resumes/create/userInfo/index.tsx
  mozip-client/src/hooks/useResumes.tsx
  mozip-client/src/modules/index.ts
  mozip-client/src/modules/resumes/actions.ts
  mozip-client/src/modules/resumes/reducer.ts
  mozip-client/src/modules/resumes/sagas.ts
Labels: FE, feature

#114 유저 회원가입, 로그인, 로그아웃, 로그인 유지
  mozip-client/src/components/common/Header/index.scss
  mozip-client/src/components/common/Header/index.tsx
  mozip-client/src/components/common/InputForm/index.tsx
  mozip-client/src/containers/SignIn/SignInContainer/index.tsx
  mozip-client/src/containers/SignUp/Applicant/index.tsx
  mozip-client/src/containers/SignUp/Manager/index.tsx
  mozip-client/src/containers/SignUp/SignUpContainer/index.tsx
  mozip-client/src/containers/SignUp/SignUpContainer/style.ts
  mozip-client/src/hooks/index.ts
  mozip-client/src/hooks/useUsers.ts
  mozip-client/src/modules/index.ts
  mozip-client/src/modules/users/actions.ts
  mozip-client/src/modules/users/index.ts
  mozip-client/src/modules/users/reducer.ts
  mozip-client/src/modules/users/sagas.ts
  mozip-client/src/modules/users/types.ts
  mozip-client/src/pages/SignInPage.tsx
  mozip-client/src/pages/SignUpPage.tsx
Labels: FE

#126 feat: #99 리쿠르팅 목록 디자인
  mozip-client/src/components/Admin/Notice/List/index.tsx
  mozip-client/src/components/Admin/Notice/List/style.ts
  mozip-client/src/pages/AdminPage.tsx
Labels: FE

#127 feat: 회원가입 페이지 가이드 수정 반영
  mozip-client/src/components/common/Header/index.scss
  mozip-client/src/components/common/Header/index.tsx
  mozip-client/src/components/common/InputForm/style.ts
  mozip-client/src/containers/SignUp/SignUpContainer/index.tsx
  mozip-client/src/containers/SignUp/SignUpContainer/style.ts
  mozip-client/src/index.css
  mozip-client/src/static/images/sign-logo.png
Labels: FE

#129 [ Fix - 2차 수정 ] Resume API & Domain
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/controller/ResumeController.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeAnswerItemCreateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeAnswerItemUpdateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeAnswerItemViewDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeStateUpdateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeViewDtoById.java
  mozip-server/mozip-api/src/test/java/org/nexters/mozipmozip/resume/ResumeControllerTest.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/application/ResumeService.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/ResumeAnswerItem.java
Labels: BE

#124 Feature/issue 115
  mozip-client/src/components/common/inputBox/index.tsx
  mozip-client/src/components/common/inputBox/styled.ts
  mozip-client/src/components/users/CheckBox/index.tsx
  mozip-client/src/components/users/CheckBox/styled.ts
  mozip-client/src/components/users/answerBox/index.tsx
  mozip-client/src/components/users/inputBox/index.tsx
  mozip-client/src/components/users/inputBox/styled.ts
  mozip-client/src/components/users/resumes/create/answers/index.tsx
  mozip-client/src/components/users/resumes/create/userInfo/index.tsx
  mozip-client/src/components/users/resumes/create/userInfo/styled.ts
  mozip-client/src/pages/Resumes.tsx
Labels: FE, feature

#130 [ Develop to Master ] Resume 2차 수정
  mozip-client/src/components/common/inputBox/index.tsx
  mozip-client/src/components/common/inputBox/styled.ts
  mozip-client/src/components/users/CheckBox/index.tsx
  mozip-client/src/components/users/CheckBox/styled.ts
  mozip-client/src/components/users/answerBox/index.tsx
  mozip-client/src/components/users/inputBox/index.tsx
  mozip-client/src/components/users/inputBox/styled.ts
  mozip-client/src/components/users/resumes/create/answers/index.tsx
  mozip-client/src/components/users/resumes/create/userInfo/index.tsx
  mozip-client/src/components/users/resumes/create/userInfo/styled.ts
  mozip-client/src/pages/Resumes.tsx
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/controller/ResumeController.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeAnswerItemCreateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeAnswerItemUpdateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeAnswerItemViewDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeStateUpdateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeViewDtoById.java
  mozip-server/mozip-api/src/test/java/org/nexters/mozipmozip/resume/ResumeControllerTest.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/application/ResumeService.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/ResumeAnswerItem.java
Labels: BE

#136 Feature/issue 133
  mozip-client/src/components/users/CheckBox/styled.ts
  mozip-client/src/components/users/answerBox/index.tsx
  mozip-client/src/components/users/resumes/create/answers/index.tsx
  mozip-client/src/components/users/resumes/create/complete/index.tsx
  mozip-client/src/components/users/resumes/create/complete/styled.ts
  mozip-client/src/components/users/resumes/create/index.tsx
  mozip-client/src/components/users/resumes/create/userInfo/index.tsx
  mozip-client/src/containers/Main/MainContainer/index.tsx
  mozip-client/src/hooks/useResumes.tsx
  mozip-client/src/modules/index.ts
  mozip-client/src/modules/resumes/actions.ts
  mozip-client/src/modules/resumes/reducer.ts
Labels: FE, feature

#138 [ Develop to Master ] 지원서 API & Domain 수정
  mozip-client/package.json
  mozip-client/src/components/Admin/Notice/Create/Result/index.tsx
  mozip-client/src/components/Admin/Notice/Create/Result/style.ts
  mozip-client/src/components/Admin/Notice/Detail/index.tsx
  mozip-client/src/components/Admin/Notice/Detail/styled.ts
  mozip-client/src/components/Admin/Notice/List/index.tsx
  mozip-client/src/components/Admin/Notice/List/style.ts
  mozip-client/src/components/Admin/Notice/index.ts
  mozip-client/src/components/Admin/Progress/List/index.tsx
  mozip-client/src/components/common/Admin/Calendar/Calendar.tsx
  mozip-client/src/components/common/Header/index.tsx
  mozip-client/src/components/users/CheckBox/styled.ts
  mozip-client/src/components/users/answerBox/index.tsx
  mozip-client/src/components/users/resumes/create/answers/index.tsx
  mozip-client/src/components/users/resumes/create/complete/index.tsx
  mozip-client/src/components/users/resumes/create/complete/styled.ts
  mozip-client/src/components/users/resumes/create/index.tsx
  mozip-client/src/components/users/resumes/create/userInfo/index.tsx
  mozip-client/src/containers/Main/MainContainer/index.tsx
  mozip-client/src/containers/SignIn/SignInContainer/index.tsx
  mozip-client/src/hooks/useAdmin.tsx
  mozip-client/src/hooks/useBlockIfNotLogin.tsx
  mozip-client/src/hooks/useResumes.tsx
  mozip-client/src/lib/axios.ts
  mozip-client/src/modules/admin/actions.ts
  mozip-client/src/modules/admin/reducer.ts
  mozip-client/src/modules/admin/sagas.ts
  mozip-client/src/modules/admin/types.ts
  mozip-client/src/modules/index.ts
  mozip-client/src/modules/resumes/actions.ts
  mozip-client/src/modules/resumes/reducer.ts
  mozip-client/src/modules/resumes/sagas.ts
  mozip-client/src/modules/users/reducer.ts
  mozip-client/src/modules/users/sagas.ts
  mozip-client/src/pages/AdminPage.tsx
  mozip-client/yarn.lock
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/controller/ResumeController.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeCreateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeUpdateDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeViewDto.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeViewDtoById.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeViewDtoByNoticeId.java
  mozip-server/mozip-api/src/main/java/org/nexters/mozipmozip/resume/dto/ResumeViewDtoByUserId.java
  mozip-server/mozip-api/src/test/java/org/nexters/mozipmozip/resume/ResumeControllerTest.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/Resume.java
  mozip-server/mozip-domain/src/main/java/org/nexters/mozipmozip/resume/domain/ResumeJobType.java
  mozip-server/mozip-domain/src/main/resources/data.sql
  mozip-server/mozip-domain/src/test/java/org/nexters/mozipmozip/resume/application/ResumeServiceTest.java
Labels: BE, FE

#139 히스토리 버그 수정, 임시 이미지 데이터
  mozip-client/src/components/Admin/Notice/Create/Intro/index.tsx
  mozip-client/src/components/Admin/Notice/Create/Intro/styled.ts
  mozip-client/src/components/Admin/Notice/Create/Result/index.tsx
  mozip-client/src/components/Admin/Notice/Detail/index.tsx
  mozip-client/src/components/common/Header/index.tsx
  mozip-client/src/containers/SignIn/SignInContainer/index.tsx
  mozip-client/src/hooks/useUsers.ts
  mozip-client/src/modules/admin/reducer.ts
  mozip-client/src/modules/users/actions.ts
  mozip-client/src/modules/users/reducer.ts
  mozip-client/src/modules/users/types.ts
  mozip-client/src/pages/AdminPage.tsx
  mozip-client/src/pages/MainPage.tsx
  mozip-client/src/static/images/cats.jpeg
Labels: FE
